// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: angry.proto

package protos

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Body string `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_angry_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_angry_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_angry_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

var File_angry_proto protoreflect.FileDescriptor

var file_angry_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x61, 0x6e, 0x67, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x61,
	0x6e, 0x67, 0x72, 0x79, 0x22, 0x1d, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62,
	0x6f, 0x64, 0x79, 0x32, 0x3c, 0x0a, 0x0c, 0x41, 0x6e, 0x67, 0x72, 0x79, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x2c, 0x0a, 0x08, 0x47, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x12,
	0x0e, 0x2e, 0x61, 0x6e, 0x67, 0x72, 0x79, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a,
	0x0e, 0x2e, 0x61, 0x6e, 0x67, 0x72, 0x79, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22,
	0x00, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_angry_proto_rawDescOnce sync.Once
	file_angry_proto_rawDescData = file_angry_proto_rawDesc
)

func file_angry_proto_rawDescGZIP() []byte {
	file_angry_proto_rawDescOnce.Do(func() {
		file_angry_proto_rawDescData = protoimpl.X.CompressGZIP(file_angry_proto_rawDescData)
	})
	return file_angry_proto_rawDescData
}

var file_angry_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_angry_proto_goTypes = []interface{}{
	(*Message)(nil), // 0: angry.Message
}
var file_angry_proto_depIdxs = []int32{
	0, // 0: angry.AngryService.Greeting:input_type -> angry.Message
	0, // 1: angry.AngryService.Greeting:output_type -> angry.Message
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_angry_proto_init() }
func file_angry_proto_init() {
	if File_angry_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_angry_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_angry_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_angry_proto_goTypes,
		DependencyIndexes: file_angry_proto_depIdxs,
		MessageInfos:      file_angry_proto_msgTypes,
	}.Build()
	File_angry_proto = out.File
	file_angry_proto_rawDesc = nil
	file_angry_proto_goTypes = nil
	file_angry_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AngryServiceClient is the client API for AngryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AngryServiceClient interface {
	Greeting(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error)
}

type angryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAngryServiceClient(cc grpc.ClientConnInterface) AngryServiceClient {
	return &angryServiceClient{cc}
}

func (c *angryServiceClient) Greeting(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/angry.AngryService/Greeting", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AngryServiceServer is the server API for AngryService service.
type AngryServiceServer interface {
	Greeting(context.Context, *Message) (*Message, error)
}

// UnimplementedAngryServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAngryServiceServer struct {
}

func (*UnimplementedAngryServiceServer) Greeting(context.Context, *Message) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Greeting not implemented")
}

func RegisterAngryServiceServer(s *grpc.Server, srv AngryServiceServer) {
	s.RegisterService(&_AngryService_serviceDesc, srv)
}

func _AngryService_Greeting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AngryServiceServer).Greeting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/angry.AngryService/Greeting",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AngryServiceServer).Greeting(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

var _AngryService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "angry.AngryService",
	HandlerType: (*AngryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Greeting",
			Handler:    _AngryService_Greeting_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "angry.proto",
}
